#!/usr/bin/env bash
set -u
set -e

DL_VERSION=54
DL_DIR="/var/log/dailylog"
DL_DAILY_FILE="${DL_DIR}/daily.log"
DL_VERSION_FILE="${DL_DIR}/.version"
DL_GIT_REPO="https://github.com/lukasdanckwerth/dailylog.git"
DL_GIT_INSTALL_SCRIPT="https://raw.githubusercontent.com/lukasdanckwerth/dailylog/main/install-dailylog.sh"

emph() {
  echo "\033[1m${*}\033[0m"
}

die() {
  echo -e "${*}" && exit 0
}

die_error() {
  echo "" && echo -e "$(emph "ERROR:") ${*}" && echo "" && exit 0
}

remote_version() {
  git ls-remote "${DL_GIT_REPO}" HEAD | awk '{ print $1}'
}

local_version() {
  if [[ -f "${DL_VERSION_FILE}" ]]; then echo "$(cat "${DL_VERSION_FILE}")"; else echo ""; fi
}

year_dir() {
  echo "${DL_DIR}/$(date +%Y)"
}

weekly_log_file() {
  echo "$(year_dir)/$(date +%V).log"
}

create_dir() {
  [[ -d "${1}" ]] || sudo mkdir -p "${1}"
  sudo chmod 777 "${1}"
}

create_file() {
  [[ -f "${1}" ]] || touch "${1}"
  # chown ${dl_user_name}:${dl_user_name} "${file_path}"
  # sudo chmod 777 "${1}"
}

recreate_dailylog() {
  rm -rf "${DL_DAILY_FILE}" && create_file "${DL_DAILY_FILE}"
}

show_weekly_log() {
  local LOG_FILE="$(weekly_log_file)" && echo -e "${LOG_FILE}\n" && tail "${LOG_FILE}"
}

update_dailylog() {
  sudo /bin/bash -c "$(curl -fsSL "${DL_GIT_INSTALL_SCRIPT}")"
  dailylog --version
}

print_help() {
  echo -e "
usage: dailylog <text> [<argument>]

    $(emph "--label     | -b") label    The label of the log message.
    $(emph "--level     | -l") level    The level of the log message.

    $(emph "--l-info    | -li")         Sets the level to INFO.
    $(emph "--l-warning | -lw")         Sets the level to WARN.
    $(emph "--l-error   | -le")         Sets the level to ERRO.

    $(emph "--remove    | -r")          Removes the dailylog file.
    $(emph "--week")                    Shows the weekly log.
    $(emph "--quite     | -q")          Do not print message on console.
    $(emph "--dry       | -d")          Do not write message to files.
    $(emph "--help      | -h")          Prints this help and exists.
"
}

if [ "${#}" -eq "0" ]; then
  [[ -f "${DL_DAILY_FILE}" ]] || die_error "file ${DL_DAILY_FILE} not existing"
  tail "${DL_DAILY_FILE}" && exit 0
fi

DL_DATE_FORMAT="+%H:%M:%S.%4N"
DL_LABEL=""
DL_LEVEL=""
DL_ARGUMENTS=""

DL_QUIET="0"
DL_DRY="0"

while (($# > 0)); do
  opt="${1}"
  shift
  case $opt in
  --label | -b)
    DL_LABEL="${1}"
    shift
    ;;
  --level | -l)
    DL_LEVEL="${1}"
    shift
    ;;
  --l-error | -le)
    DL_LEVEL="ERRO"
    ;;
  --l-warning | -lw)
    DL_LEVEL="WARN"
    ;;
  --l-info | -li)
    DL_LEVEL="INFO"
    ;;
  --date-format | -df)
    DL_DATE_FORMAT="${1}"
    shift
    ;;
  --dry | -d)
    DL_DRY="1"
    ;;
  --quite | -q)
    DL_QUIET="1"
    ;;
  --week | -w)
    show_weekly_log && exit 0
    ;;
  --remove | -r)
    recreate_dailylog && exit 0
    ;;
  --help | -h)
    print_help && exit 0
    ;;
  --update | -u)
    update_dailylog && exit 0
    ;;
  --version | -v)
    echo -e "version:      ${DL_VERSION}"
    echo -e "local hash:   $(local_version)"
    echo -e "remote hash:  $(remote_version)" && exit 0
    ;;
  *)
    DL_ARGUMENTS="${DL_ARGUMENTS} ${opt}"
    ;;
  esac
done

# create base dir (if not existing)
[[ -d "${DL_DIR}" ]] || create_dir "${DL_DIR}"

# create dailylog file (if not existing)
[[ -f "${DL_DAILY_FILE}" ]] || create_file "${DL_DAILY_FILE}"

DL_DATE="$(date "${DL_DATE_FORMAT}")"

# build log message
DL_MESSAGE="${DL_DATE}"

# append label to message
[[ "${DL_LABEL}" == "" ]] || DL_MESSAGE="${DL_MESSAGE} ::  [${DL_LABEL}]"

[[ "${DL_LEVEL}" == "" ]] && (DL_LEVEL="    ")
DL_MESSAGE="${DL_MESSAGE} : [${DL_LEVEL}]"
DL_MESSAGE="${DL_MESSAGE} : ${DL_ARGUMENTS}"

# year directory
DL_YEAR_DIR="$(year_dir)"
[[ -d "${DL_YEAR_DIR}" ]] || create_dir "${DL_YEAR_DIR}"

# weekly log
DL_WEEK_LOG="$(weekly_log_file)"
[[ -f "${DL_WEEK_LOG}" ]] || create_file "${DL_WEEK_LOG}"

# print message on console (if not set to quite)
[[ "${DL_QUIET}" == "1" ]] || echo "${DL_MESSAGE}"

# append message to daily log file
[[ "${DL_DRY}" == "1" ]] || echo "${DL_MESSAGE}" >>"${DL_DAILY_FILE}"

# append message to weekly log file
[[ "${DL_DRY}" == "1" ]] || echo "${DL_MESSAGE}" >>"${DL_WEEK_LOG}"
